  {
    id: 133,
    name: "ESS Flip ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 174.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Simple, sporty, and summer-ready. These flip-flops deliver lightweight comfort for casual days.",
    image: "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_2_0c0b7d4831.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_4_74876527a6.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_2_0c0b7d4831.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_4_74876527a6.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_7_97eaa37df6.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_8_941f909366.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder/puma_10_343a5a652f.png"
    ],
    slug: "ess-flip-zadp-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 134,
    name: "ESS Flip ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 174.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Simple, sporty, and summer-ready. These flip-flops deliver lightweight comfort for casual days.",
    image: "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_4_f50d499585.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_6_0388dc7189.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_4_f50d499585.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_6_0388dc7189.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_7_96ba613899.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_8_2601de88c9.png",
      "shop/Slides-Sandals/Puma/men/ESS Flip ZADP/ess-flip-zadp/New folder (2)/puma_10_bb69def45c.png"
    ],
    slug: "ess-flip-zadp-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 135,
    name: "First Flip Formstrip ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 249.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "First Flip Formstrip ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_1_2ed4cb92e8.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_2_dfc3fdfc83.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_1_2ed4cb92e8.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_2_dfc3fdfc83.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_3_b28f386936.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_4_4cd3adf197.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_5_a0767538be.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_6_5c37ac207b.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_7_580afd97c8.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_8_b4cb320cc8.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_9_39aef6b723.png",
      "shop/Slides-Sandals/Puma/men/First Flip Formstrip ZADP/first-flip-formstrip-zadp/puma_10_105e89802f.png"
    ],
    slug: "first-flip-formstrip-zadp",
    isNew: false,
    isSale: false,
  },
  {
    id: 136,
    name: "Poolcat Slide Focus ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 449.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Core footwear collection is all about simplicity, style, and versatility.",
    image: "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_1_20bc80d810.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_2_3ddfa7782d.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_1_20bc80d810.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_2_3ddfa7782d.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_3_53a89f8133.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_4_2b5b8dcdce.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder/puma_5_b639066a26.png"
    ],
    slug: "poolcat-slide-focus-zadp-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 137,
    name: "Poolcat Slide Focus ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 449.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Core footwear collection is all about simplicity, style, and versatility.",
    image: "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_1_a4b2a802df.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_2_cc9c7b3d9e.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_1_a4b2a802df.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_2_cc9c7b3d9e.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_3_f81d07d8a0.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_4_c81a8a5e88.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/New folder (2)/puma_5_0575ab43c2.png"
    ],
    slug: "poolcat-slide-focus-zadp-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 138,
    name: "Poolcat Slide Velcro ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 499.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Poolcat Slide Velcro ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_1_3889d455bb.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_2_01bdd04b0a.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_1_3889d455bb.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_2_01bdd04b0a.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_3_3727f67ba2.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_4_a64cc226a9.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder/puma_5_a365f30f87.png"
    ],
    slug: "poolcat-slide-velcro-zadp-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 139,
    name: "Poolcat Slide Velcro ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 499.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Poolcat Slide Velcro ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_1_ae8d4f4127.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_2_79ef69507f.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_1_ae8d4f4127.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_2_79ef69507f.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_3_47036b6654.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_4_5aaac4ecfe.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide Velcro ZADP/poolcat-slide-velcro-zadp/New folder (2)/puma_5_175c05375a.png"
    ],
    slug: "poolcat-slide-velcro-zadp-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 140,
    name: "Poolcat Slide ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 499.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Poolcat Slide ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_1_2fc996e126.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_2_91cb066a54.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_1_2fc996e126.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_2_91cb066a54.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_3_74aa76eb14.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_4_c5bd28ea73.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder/puma_5_cad00038e1.png"
    ],
    slug: "poolcat-slide-zadp-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 141,
    name: "Poolcat Slide ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 499.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Poolcat Slide ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_1_c926e9d593.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_2_d408a730a9.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_1_c926e9d593.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_2_d408a730a9.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_3_313fa91956.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_4_f55be38c93.png",
      "shop/Slides-Sandals/Puma/men/Poolcat Slide ZADP/poolcat-slide-zadp/New folder (2)/puma_5_99f05081c6.png"
    ],
    slug: "poolcat-slide-zadp-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 142,
    name: "Sporty Embossed 2.0 Slides Men",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 258.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Lightweight, comfortable, and effortlessly cool—the PUMA Sporty Slides are your go-to for everyday wear. Designed with a cushioned footbed, they’re perfect for post-workout relaxation, poolside lounging, or casual outings. Just slide in and keep moving!",
    image: "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_1_b0d5fac307.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_2_e1ac67b6b0.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_1_b0d5fac307.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_2_e1ac67b6b0.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_3_f2c2c05d0b.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_4_c3bab54aca.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_5_dc6044ab3f.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_6_169200462a.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_7_7b1f07f88f.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_8_c8c5674ac6.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_9_4217eea786.png",
      "shop/Slides-Sandals/Puma/men/Sporty Embossed 2.0 Slides Men/sporty-embossed-2-0-slides-men/puma_10_fb647602c0.png"
    ],
    slug: "sporty-embossed-2-0-slides-men",
    isNew: false,
    isSale: false,
  },
  {
    id: 143,
    name: "Sporty Magnet TW Slides Men",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 379.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Lightweight, comfortable, and effortlessly cool—the PUMA Sporty Slides are your go-to for everyday wear. Designed with a cushioned footbed, they’re perfect for post-workout relaxation, poolside lounging, or casual outings. Just slide in and keep moving!",
    image: "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_1_56e7ff863a.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_2_77444ed479.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_1_56e7ff863a.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_2_77444ed479.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_3_7f1ca0b9a6.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_4_d91c2a3107.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder/puma_5_3c9daf506f.png"
    ],
    slug: "sporty-magnet-tw-slides-men-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 144,
    name: "Sporty Magnet TW Slides Men",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 379.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Lightweight, comfortable, and effortlessly cool—the PUMA Sporty Slides are your go-to for everyday wear. Designed with a cushioned footbed, they’re perfect for post-workout relaxation, poolside lounging, or casual outings. Just slide in and keep moving!",
    image: "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_1_ccbd9413eb.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_2_2d78fc79a7.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_1_ccbd9413eb.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_2_2d78fc79a7.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_3_fe82d215d0.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_4_53873a9c93.png",
      "shop/Slides-Sandals/Puma/men/Sporty Magnet TW Slides Men/sporty-magnet-tw-slides-men/New folder (2)/puma_5_605a72c9be.png"
    ],
    slug: "sporty-magnet-tw-slides-men-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 145,
    name: "Wve Mule 360 Sneakers Unisex",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 1099.00,
    currency: "ZAR",
    salePrice: null,
    category: ["men","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Slide into all-weather versatility with moulded EVA construction for a snug fit. Featuring a textured footbed for day-long ease and bottom grooves for unbeatable grip. Water-resistant and breathable, they're your go-to for everything from lazy Sundays to spontaneous activities. Classic PUMA energy with every move.",
    image: "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_1_d78e6861a0.png",
    hoverImage: "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_2_a9fee66235.png",
    allImages: [
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_1_d78e6861a0.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_2_a9fee66235.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_3_861f6228bf.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_4_b34f7991a3.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_5_c556f4dc45.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_6_5c4df1347a.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_7_e0b4dd6c28.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_8_3cac476162.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_9_f7322d3090.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_10_9f9c744423.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_11_9ac2f3cd9f.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_12_97a8ccb4e4.png",
      "shop/Slides-Sandals/Puma/men/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/puma_13_0bed22bc59.png"
    ],
    slug: "wve-mule-360-sneakers-unisex",
    isNew: false,
    isSale: false,
  },
  {
    id: 146,
    name: "ESS flip Wns ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 225.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "ESS flip Wns ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_1_2bf0a28cbd.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_2_9ffb115c1f.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_1_2bf0a28cbd.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_2_9ffb115c1f.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_4_a3f23f52a6.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_5_b051848e55.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder/puma_8_7911742d32.png"
    ],
    slug: "ess-flip-wns-zadp-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 147,
    name: "ESS flip Wns ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 225.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "ESS flip Wns ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_1_82c9b1b668.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_2_c3ff1509ab.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_1_82c9b1b668.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_2_c3ff1509ab.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_3_106dd3a8ca.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_4_8da7dba08e.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (2)/puma_5_6f64307b66.png"
    ],
    slug: "ess-flip-wns-zadp-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 148,
    name: "ESS flip Wns ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 225.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "ESS flip Wns ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_1_6334b03a17.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_2_a93ac0781b.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_1_6334b03a17.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_2_a93ac0781b.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_3_16b5e28158.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_5_e168ab23fe.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (3)/puma_7_e9dbcdaa1f.png"
    ],
    slug: "ess-flip-wns-zadp-3",
    isNew: false,
    isSale: false,
  },
  {
    id: 149,
    name: "ESS flip Wns ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 225.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "ESS flip Wns ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_1_497d6f7155.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_2_0769c1b35a.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_1_497d6f7155.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_2_0769c1b35a.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_4_9b18ca110b.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_5_7840630075.png",
      "shop/Slides-Sandals/Puma/women/ESS flip Wns ZADP/ess-flip-wns-zadp/New folder (4)/puma_8_8e2100bf81.png"
    ],
    slug: "ess-flip-wns-zadp-4",
    isNew: false,
    isSale: false,
  },
  {
    id: 150,
    name: "First Flip Stacked Sandals Women",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 399.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Flip is your go-to for laid-back style and all-day comfort. Designed for sunny days and easy-going vibes, these slides let you step into relaxation with a touch of sporty flair. Whether you're lounging by the pool or strolling along the beach, the Flip keep you cool and casual. Flip into comfort, and let the good times roll!",
    image: "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_1_e29d0f1393.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_2_124f22d5c1.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_1_e29d0f1393.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_2_124f22d5c1.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_3_ca43fbfdc7.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_4_3dd067a7e8.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_5_5159ecf697.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_6_56bbfd602c.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_7_06e58b0165.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_8_42825cf667.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_9_dc696801b1.png",
      "shop/Slides-Sandals/Puma/women/First Flip Stacked Sandals Women/first-flip-stacked-sandals-women/puma_10_3b139ef6d5.png"
    ],
    slug: "first-flip-stacked-sandals-women",
    isNew: false,
    isSale: false,
  },
  {
    id: 151,
    name: "Hypnotic Sandal DayINight Sneakers Women",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 1049.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Hypnotic sneakers are designed for those who crave style with a sporty edge. With their dynamic look and comfortable fit, these sneakers make every step comfortable. Whether you're hitting the streets or just stepping out for the day, stay cool, stay confident, and let the Hypnotic keep you in motion – wherever life takes you.",
    image: "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_1_4bcbc0bd2b.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_2_18724b8fa2.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_1_4bcbc0bd2b.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_2_18724b8fa2.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_3_403618dd30.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_4_e05be7723a.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_5_d2386659f2.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder/puma_6_3ef13ec232.png"
    ],
    slug: "hypnotic-sandal-dayinight-sneakers-women-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 152,
    name: "Hypnotic Sandal DayINight Sneakers Women",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 1049.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Hypnotic sneakers are designed for those who crave style with a sporty edge. With their dynamic look and comfortable fit, these sneakers make every step comfortable. Whether you're hitting the streets or just stepping out for the day, stay cool, stay confident, and let the Hypnotic keep you in motion – wherever life takes you.",
    image: "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_1_4621ac0036.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_2_9e1f6116e8.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_1_4621ac0036.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_2_9e1f6116e8.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_3_1c663377ef.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_4_8c7600b955.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_5_1f640dff5c.png",
      "shop/Slides-Sandals/Puma/women/Hypnotic Sandal DayINight Sneakers Women/hypnotic-sandal-dayinight-sneakers-women/New folder (2)/puma_6_e06723ad1e.png"
    ],
    slug: "hypnotic-sandal-dayinight-sneakers-women-2",
    isNew: false,
    isSale: false,
  },
  {
    id: 153,
    name: "Poolcat Slide Focus ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 314.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Core footwear collection is all about simplicity, style, and versatility.",
    image: "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_1_20bc80d810.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_2_3ddfa7782d.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_1_20bc80d810.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_2_3ddfa7782d.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_3_53a89f8133.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_4_2b5b8dcdce.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_5_b639066a26.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_6_6a65a330d1.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_7_8e670dc37c.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_8_6ac83dcb6c.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_9_be61631727.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_10_b476e5a3d1.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slide Focus ZADP/poolcat-slide-focus-zadp/puma_11_68cbecd0c4.png"
    ],
    slug: "poolcat-slide-focus-zadp",
    isNew: false,
    isSale: false,
  },
  {
    id: 154,
    name: "Poolcat Slides Women",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 449.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "The PUMA Core footwear collection is all about simplicity, style, and versatility. Crafted for those who appreciate the essentials, these sneakers bring a clean, no-fuss design with all-day comfort. Whether you're running errands, meeting friends, or just strolling through the city, the Core collection is your go-to for effortless style that works with anything. Timeless, reliable, and ready for anything – because sometimes, the best things are the simplest.",
    image: "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_1_7a322267d4.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_2_4702f5799b.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_1_7a322267d4.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_2_4702f5799b.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_3_2053e71acb.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_4_515ba790e2.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_5_262e431a36.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_6_f3397990c5.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_7_4e0e27af80.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_8_d6a5e95625.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_9_4c170bef3a.png",
      "shop/Slides-Sandals/Puma/women/Poolcat Slides Women/poolcat-slides-women/puma_10_75ab644505.png"
    ],
    slug: "poolcat-slides-women",
    isNew: false,
    isSale: false,
  },
  {
    id: 155,
    name: "PUMA Flatter Sandals Women",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 680.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Slide into summer vibes with the PUMA Flatter sandals. Featuring a moulded footbed and platform sole, they offer cushioning and comfort with every step. Perfect for those who love a relaxed summer look.",
    image: "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_1_cd598a6013.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_2_6dc40c526f.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_1_cd598a6013.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_2_6dc40c526f.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_3_9cd7872335.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_4_25bf0c4681.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_5_86ccf68789.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_6_7bd77e2cfd.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_7_071fa5156d.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_8_d5f0682c88.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_9_bd3ab1d719.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_10_d1e2257ce2.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_11_1ab7c09cf2.png",
      "shop/Slides-Sandals/Puma/women/PUMA Flatter Sandals Women/puma-flatter-sandals-women/puma_12_71fea4145f.png"
    ],
    slug: "puma-flatter-sandals-women",
    isNew: false,
    isSale: false,
  },
  {
    id: 156,
    name: "Style Bolero 2.0 Sneakers Women",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 349.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Slip into effortless style with a synthetic leather upper that blends sleek design with easy wear. A padded footbed adds all-day comfort, while the TPR outsole keeps you grounded wherever life takes you. Feminine vibes meet PUMA DNA—perfect for sunny strolls or laid-back weekends. Always PUMA, always bold.",
    image: "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_1_a9d2e118e8.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_2_6f593eeb38.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_1_a9d2e118e8.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_2_6f593eeb38.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_3_6717497aef.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_4_7760b9c684.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_5_2d397d9838.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_6_f9e9ea399b.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_7_4e6c9f7759.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_8_ee9143a204.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_9_29eec70b2e.png",
      "shop/Slides-Sandals/Puma/women/Style Bolero 2.0 Sneakers Women/style-bolero-2-0-sneakers-women/puma_10_7063782e83.png"
    ],
    slug: "style-bolero-2-0-sneakers-women",
    isNew: false,
    isSale: false,
  },
  {
    id: 157,
    name: "StylecatSleek Injex Wns ZADP",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 299.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "StylecatSleek Injex Wns ZADP by PUMA.",
    image: "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_1_2383f76f20.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_2_765a00bd80.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_1_2383f76f20.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_2_765a00bd80.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_3_b89daac8b1.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_4_f9182ba173.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_5_9f415b654e.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_6_d82f87c765.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_7_812037aad9.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_8_0c9f254e3c.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_9_8a234011ed.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_10_d2e025ec0f.png",
      "shop/Slides-Sandals/Puma/women/StylecatSleek Injex Wns ZADP/stylecatsleek-injex-wns-zadp/puma_11_b834efeb6e.png"
    ],
    slug: "stylecatsleek-injex-wns-zadp",
    isNew: false,
    isSale: false,
  },
  {
    id: 158,
    name: "Wve Mule 360 Sneakers Unisex",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 1099.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Slide into all-weather versatility with moulded EVA construction for a snug fit. Featuring a textured footbed for day-long ease and bottom grooves for unbeatable grip. Water-resistant and breathable, they're your go-to for everything from lazy Sundays to spontaneous activities. Classic PUMA energy with every move.",
    image: "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_1_c550469e55.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_2_d8c955f62b.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_1_c550469e55.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_2_d8c955f62b.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_3_c79ffde09f.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_4_73d4d94da7.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_5_43d992a1b0.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder/puma_6_288e8045c5.png"
    ],
    slug: "wve-mule-360-sneakers-unisex-1",
    isNew: false,
    isSale: false,
  },
  {
    id: 159,
    name: "Wve Mule 360 Sneakers Unisex",
    sku: "",
    brand: "PUMA",
    collection: "",
    price: 1099.00,
    currency: "ZAR",
    salePrice: null,
    category: ["women","slides"],
    sizes: ["36","37","38","39","40","41","42","43","44","45","46"],
    color: "",
    description: "Slide into all-weather versatility with moulded EVA construction for a snug fit. Featuring a textured footbed for day-long ease and bottom grooves for unbeatable grip. Water-resistant and breathable, they're your go-to for everything from lazy Sundays to spontaneous activities. Classic PUMA energy with every move.",
    image: "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_1_d78e6861a0.png",
    hoverImage: "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_2_a9fee66235.png",
    allImages: [
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_1_d78e6861a0.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_2_a9fee66235.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_3_861f6228bf.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_4_b34f7991a3.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_5_c556f4dc45.png",
      "shop/Slides-Sandals/Puma/women/Wve Mule 360 Sneakers Unisex/wve-mule-360-sneakers-unisex/New folder (2)/puma_6_5c4df1347a.png"
    ],
    slug: "wve-mule-360-sneakers-unisex-2",
    isNew: false,
    isSale: false,
  }